Repository ollionorg/flow-core, pull requests merged in 2023-07, with the labels that each got.

#86 FLOW-808 FLOW-809 FLOW-804 bug fixes
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.scss
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.ts
  packages/flow-core/src/components/f-button/f-button.scss
  packages/flow-core/src/components/f-checkbox/f-checkbox.scss
  packages/flow-core/src/components/f-checkbox/f-checkbox.ts
  packages/flow-core/src/components/f-counter/f-counter.scss
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.scss
  packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.scss
  packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.ts
  packages/flow-core/src/components/f-field/f-field.scss
  packages/flow-core/src/components/f-file-upload/f-file-upload.scss
  packages/flow-core/src/components/f-file-upload/f-file-upload.ts
  packages/flow-core/src/components/f-icon-button/f-icon-button.scss
  packages/flow-core/src/components/f-icon/f-icon.scss
  packages/flow-core/src/components/f-icon/f-icon.ts
  packages/flow-core/src/components/f-input/f-input.scss
  packages/flow-core/src/components/f-input/f-input.ts
  packages/flow-core/src/components/f-pictogram/f-pictogram.scss
  packages/flow-core/src/components/f-radio/f-radio.scss
  packages/flow-core/src/components/f-radio/f-radio.ts
  packages/flow-core/src/components/f-search/f-search.scss
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-select/f-select.scss
  packages/flow-core/src/components/f-select/render.ts
  packages/flow-core/src/components/f-switch/f-switch.scss
  packages/flow-core/src/components/f-switch/f-switch.ts
  packages/flow-core/src/components/f-text-area/f-text-area.scss
  packages/flow-core/src/components/f-text-area/f-text-area.ts
  packages/flow-core/src/components/f-text/f-text.ts
  packages/flow-core/src/mixins/components/f-root/f-root.scss
  packages/flow-core/src/mixins/scss/_mixins.scss
  packages/flow-table/custom-elements.json
  stories/f-button.stories.mdx
  stories/f-div.stories.mdx
  stories/f-icon.stories.mdx
  stories/f-switch.stories.mdx
Labels: size/XXL, lgtm

#85 FLOW-803 | Bug Fixes
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-progress-bar/f-progress-bar.scss
  packages/flow-core/src/components/f-select/f-select.scss
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/render.ts
  packages/flow-table/custom-elements.json
  stories/f-select.stories.mdx
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#88 FLOW-817 sorting of rows fixed when search term is present in schema based table
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-checkbox/f-checkbox.scss
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.scss
  packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.scss
  packages/flow-core/src/components/f-icon-button/f-icon-button.scss
  packages/flow-core/src/components/f-radio/f-radio.scss
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-select/f-select.scss
  packages/flow-core/src/components/f-switch/f-switch.scss
  packages/flow-core/src/components/f-text-area/f-text-area.scss
  packages/flow-table/CHANGELOG.md
  packages/flow-table/custom-elements.json
  packages/flow-table/html.html-data.json
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/__snapshots__/f-table-schema.test.snap.js
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  packages/flow-table/src/components/f-table/f-table.scss
  packages/flow-table/src/components/f-table/f-table.ts
  packages/flow-table/src/components/f-tcell/f-tcell.ts
  packages/flow-table/src/components/f-trow/f-trow.ts
  stories/f-table-schema.stories.mdx
  stories/f-trow.stories.mdx
  stories/utils/mock-users-data.ts
Labels: size/XXL

#90 FLOW-821 Markdown content editor and viewer
  .github/workflows/release.yml
  .husky/pre-commit
  .storybook/main.js
  .storybook/preview.js
  package.json
  packages/flow-core/custom-elements.json
  packages/flow-core/src/mixins/scss/_mixins.scss
  packages/flow-md-editor/.npmignore
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-md-editor/LICENSE
  packages/flow-md-editor/README.md
  packages/flow-md-editor/compile.sh
  packages/flow-md-editor/custom-elements.json
  packages/flow-md-editor/generate-types.js
  packages/flow-md-editor/html.html-data.json
  packages/flow-md-editor/package.json
  packages/flow-md-editor/src/components/f-md-editor/__snapshots__/f-md-editor.test.snap.js
  packages/flow-md-editor/src/components/f-md-editor/f-md-editor.scss
  packages/flow-md-editor/src/components/f-md-editor/f-md-editor.test.ts
  packages/flow-md-editor/src/components/f-md-editor/f-md-editor.ts
  packages/flow-md-editor/src/components/f-md-editor/sample-md.ts
  packages/flow-md-editor/src/index.ts
  packages/flow-md-editor/src/shims.d.ts
  packages/flow-md-editor/tsconfig.json
  packages/flow-md-editor/tsconfig.node.json
  packages/flow-md-editor/vite.config.ts
  packages/flow-md-editor/web-test-runner.config.mjs
  packages/flow-table/custom-elements.json
  stories/f-md-editor.stories.mdx
  stories/utils/sample-md.ts
  yarn.lock
Labels: size/XXL

#91 FLOW-830 FLOW-832 FLOW-831 f-table-schema features and improvements
  packages/flow-core/custom-elements.json
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-md-editor/package.json
  packages/flow-md-editor/src/components/f-md-editor/f-md-editor.scss
  packages/flow-table/CHANGELOG.md
  packages/flow-table/custom-elements.json
  packages/flow-table/html.html-data.json
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/__snapshots__/f-table-schema.test.snap.js
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  packages/flow-table/src/components/f-tcell/f-tcell.ts
  packages/flow-table/src/components/f-trow/f-trow.ts
  stories/utils/mock-users-data.ts
Labels: size/XXL

#96 FLOW-845 FLOW-848 f-tcell actions callback updated
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.ts
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-tcell/f-tcell.ts
  stories/f-table-schema.stories.mdx
  stories/utils/mock-users-data.ts
Labels: size/XXL, lgtm

#104 FLOW-840 input color token implementation
  .gitignore
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-counter/f-counter.ts
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.scss
  packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.scss
  packages/flow-core/src/components/f-file-upload/f-file-upload.scss
  packages/flow-core/src/components/f-input/f-input.scss
  packages/flow-core/src/components/f-select/f-select.scss
  packages/flow-core/src/components/f-tag/f-tag.ts
  packages/flow-core/src/components/f-text-area/f-text-area.scss
  packages/flow-core/src/mixins/scss/_color-tokens.scss
  packages/flow-table/custom-elements.json
Labels: size/XXL

#106 FLOW-836 | f-pictogram should have an auto-bg flag where it auto assigns a color based on characters #97
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-pictogram/f-pictogram.scss
  packages/flow-core/src/components/f-pictogram/f-pictogram.test.ts
  packages/flow-core/src/components/f-pictogram/f-pictogram.ts
  packages/flow-table/custom-elements.json
  stories/f-pictogram.stories.mdx
Labels: size/XXL, lgtm

#107 FLOW-555 | f-text editable
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-text/f-text.scss
  packages/flow-core/src/components/f-text/f-text.ts
  packages/flow-table/custom-elements.json
  stories/f-text.stories.mdx
Labels: needs-rebase, do-not-merge/contains-merge-commits, size/XXL, lgtm

#109 108 feature request f select allow type events to be emitted from f select
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.scss
  packages/flow-core/src/components/f-select/handlers.ts
  packages/flow-core/src/mixins/components/f-root/f-root.ts
  stories/f-select.stories.mdx
Labels: size/S
