Repository ollionorg/flow-core, pull requests merged in 2023-08, with the labels that each got.

#112 FLOW-857 | f-code-editor features
  packages/flow-code-editor/CHANGELOG.md
  packages/flow-code-editor/custom-elements.json
  packages/flow-code-editor/html.html-data.json
  packages/flow-code-editor/package.json
  packages/flow-code-editor/src/components/f-code-editor/f-code-editor.scss
  packages/flow-code-editor/src/components/f-code-editor/f-code-editor.ts
  packages/flow-code-editor/src/utils/lang-comments-map.ts
  packages/flow-table/custom-elements.json
  stories/f-code-editor.stories.mdx
Labels: size/XXL, lgtm

#121 FLOW-856 | f-suggest and f-search Improvements
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-suggest/display-options.ts
  packages/flow-core/src/components/f-suggest/f-suggest.ts
  packages/flow-table/custom-elements.json
  stories/f-search.stories.mdx
  stories/f-suggest.stories.mdx
Labels: size/XXL, lgtm

#122 FLOW-866 f-select loader alignment and behavior fix
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/f-select.scss
  packages/flow-core/src/components/f-select/handlers.ts
  stories/f-select.stories.mdx
Labels: size/XXL

#123 FLOW-866 f-text host styles updated
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-text/f-text.scss
  packages/flow-table/custom-elements.json
Labels: size/XXL

#124 FLOW-868 history restored
  packages/flow-core/custom-elements.json
Labels: do-not-merge/contains-merge-commits, size/XXL

#125 FLOW-868 history restored
  packages/flow-code-editor/custom-elements.json
  packages/flow-core/custom-elements.json
  packages/flow-table/custom-elements.json
Labels: needs-rebase, do-not-merge/contains-merge-commits, size/L

#128 FLOW-700 | FLOW-604 | FLOW-799 | New Features and Improvements in f-div and f-tag
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.scss
  packages/flow-core/src/components/f-div/f-div.ts
  packages/flow-core/src/components/f-icon/f-icon.scss
  packages/flow-core/src/components/f-tag/f-tag.scss
  packages/flow-core/src/components/f-tag/f-tag.test.ts
  packages/flow-core/src/components/f-tag/f-tag.ts
  packages/flow-core/src/mixins/components/f-root/f-root.scss
  packages/flow-table/custom-elements.json
  stories/f-div.stories.mdx
  stories/f-tag.stories.mdx
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#129 FLOW-882 | FLOW-883 | f-div & f-text improvements
  packages/flow-code-editor/custom-elements.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.scss
  packages/flow-core/src/components/f-div/f-div.ts
  packages/flow-core/src/components/f-text/f-text.scss
  packages/flow-core/src/components/f-text/f-text.ts
  packages/flow-table/custom-elements.json
  stories/f-div.stories.mdx
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#127 FLOW-851 Nuxt integration Doc
  docs/nuxt3-integration.md
  packages/flow-code-editor/custom-elements.json
  packages/flow-core/custom-elements.json
  packages/flow-table/custom-elements.json
Labels: needs-rebase, do-not-merge/contains-merge-commits, size/L

#132 FLOW-888 | FLOW-892 | f-select auto-add-option AND f-text bug
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-text/f-text.scss
  packages/flow-table/custom-elements.json
  stories/f-select.stories.mdx
Labels: do-not-merge/contains-merge-commits, lgtm, size/XL
