Repository ollionorg/flow-core, pull requests merged in 2023-12, with the labels that each got.

#203 FLOW-970 f-color-picker component
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-color-picker/f-color-picker-global.scss
  packages/flow-core/src/components/f-color-picker/f-color-picker.scss
  packages/flow-core/src/components/f-color-picker/f-color-picker.test.ts
  packages/flow-core/src/components/f-color-picker/f-color-picker.ts
  packages/flow-core/src/components/f-div/f-div.ts
  packages/flow-core/src/components/f-form-field/f-form-field.ts
  packages/flow-core/src/index.ts
  packages/flow-core/vite.config.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/components/f-form-builder/fields/color.ts
  packages/flow-form-builder/src/components/f-form-builder/fields/index.ts
  packages/flow-form-builder/src/modules/helpers.ts
  packages/flow-form-builder/src/types.ts
  pnpm-lock.yaml
  stories/flow-core/f-color-picker.stories.ts
  stories/flow-form-builder/f-formbuilder-field.ts
Labels: size/XL

#204 FLOW-971 f-input typescript issue fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-input/f-input.ts
Labels: lgtm, size/S

#209 FLOW-1004 FLOW-1005 f-color-picker alignment issue fixed and hea…
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-color-picker/f-color-picker-global.scss
  packages/flow-core/src/components/f-color-picker/f-color-picker.ts
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  packages/flow-table/src/components/f-table/f-table.ts
  stories/flow-table/f-table-schema.stories.ts
Labels: size/M

#207 FLOW-972 f-log re-write
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-suggest/f-suggest.ts
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log-global.scss
  packages/flow-log/src/components/f-log/f-log-search-and-filters.ts
  packages/flow-log/src/components/f-log/f-log-utils.ts
  packages/flow-log/src/components/f-log/f-log.scss
  packages/flow-log/src/components/f-log/f-log.test.ts
  packages/flow-log/src/components/f-log/f-log.ts
  packages/flow-log/src/components/f-log/sample-logs.js
  pnpm-lock.yaml
  stories/flow-core/f-search.stories.ts
  stories/flow-log/f-log.stories.js
  stories/flow-log/f-log.stories.ts
  stories/flow-log/logs/logs.js
Labels: size/XXL, lgtm

#210 FLOW-1029 header checkbox not updating in f-table-schema
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  packages/flow-table/src/components/f-tcell/f-tcell.ts
  stories/flow-table/f-table-schema.stories.ts
Labels: lgtm, size/M

#211 FLOW-1030 scope query selector fix
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table/f-table.ts
  packages/flow-table/src/components/f-trow/f-trow.ts
Labels: size/M

#208 FLOW-969 : f-countdown component
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  packages/flow-core-config/CHANGELOG.md
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.test.ts
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.ts
  packages/flow-core/src/components/f-countdown/f-countdown.scss
  packages/flow-core/src/components/f-countdown/f-countdown.test.ts
  packages/flow-core/src/components/f-countdown/f-countdown.ts
  packages/flow-core/src/index.ts
  stories/flow-core/f-breadcrumb.mdx
  stories/flow-core/f-breadcrumb.stories.ts
  stories/flow-core/f-countdown.mdx
  stories/flow-core/f-countdown.stories.ts
  stories/flow-core/f-pictogram.stories.ts
Labels: size/XXL, lgtm

#212 FLOW-1032 tooltip attribute html rendering fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/figma/sync-colors.js
  packages/flow-core/package.json
  packages/flow-core/src/components/f-pictogram/f-pictogram.ts
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/components/f-suggest/display-options.ts
  packages/flow-core/src/components/f-text/f-text-global.scss
  packages/flow-core/src/components/f-text/f-text.ts
  packages/flow-core/src/mark.d.ts
  packages/flow-core/src/mixins/components/f-root/f-root.ts
  packages/flow-core/src/mixins/scss/_color-tokens.scss
  packages/flow-core/src/mixins/scss/_mixins.scss
  packages/flow-core/src/mixins/scss/_text-tokens.scss
  packages/flow-core/vite.config.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/components/f-checkbox-group/f-checkbox-group.ts
  packages/flow-form-builder/src/components/f-radio-group/f-radio-group.ts
  packages/flow-form-builder/src/modules/helpers.ts
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log-search-and-filters.ts
  packages/flow-log/src/mark.d.ts
  packages/flow-log/vite.config.ts
  pnpm-lock.yaml
  stories/flow-core/f-checkbox.mdx
  stories/flow-core/f-checkbox.stories.js
  stories/flow-core/f-date-time-picker.mdx
  stories/flow-core/f-date-time-picker.stories.js
  stories/flow-core/f-div.stories.js
  stories/flow-core/f-emoji-picker.mdx
  stories/flow-core/f-emoji-picker.stories.js
  stories/flow-core/f-file-upload.mdx
  stories/flow-core/f-file-upload.stories.js
  stories/flow-core/f-input.stories.ts
  stories/flow-core/f-radio.mdx
  stories/flow-core/f-radio.stories.js
  stories/flow-core/f-search.mdx
  stories/flow-core/f-search.stories.ts
  stories/flow-core/f-select.mdx
  stories/flow-core/f-select.stories.js
  stories/flow-core/f-suggest.mdx
  stories/flow-core/f-suggest.stories.ts
  stories/flow-core/f-switch.mdx
  stories/flow-core/f-switch.stories.js
  stories/flow-core/f-tab-node.mdx
  stories/flow-core/f-tab-node.stories.js
  stories/flow-core/f-text-area.mdx
  stories/flow-core/f-text-area.stories.js
  stories/flow-core/f-text.mdx
  stories/flow-core/f-text.stories.ts
  stories/flow-core/f-toast.mdx
  stories/flow-core/f-toast.stories.js
  stories/flow-core/f-tooltip.mdx
  stories/flow-core/f-tooltip.stories.ts
  stories/flow-lineage/f-lineage.mdx
  stories/flow-lineage/node-details-template.mdx
  stories/flow-lineage/node-details-template.stories.js
  stories/flow-log/f-log.mdx
Labels: size/XXL, lgtm

#214 FLOW-1037 lineage node template rendering logic updated to fix html i…
  packages/flow-lineage/CHANGELOG.md
  packages/flow-lineage/package.json
  packages/flow-lineage/src/components/f-lineage/draw/draw-nodes.ts
  packages/flow-lineage/src/components/f-lineage/draw/hot-reload-proxies.ts
  packages/flow-lineage/src/components/f-lineage/f-lineage.ts
  stories/flow-lineage/htmlinjection-test.stories.ts
  stories/flow-lineage/lineage-properties.mdx
Labels: lgtm, size/L

#213 FLOW-1036 | f-button packed category addition
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-button/f-button.scss
  packages/flow-core/src/components/f-button/f-button.ts
  stories/flow-core/f-button.stories.js
Labels: lgtm, size/S

#215 FLOW-1042 ollion theme tokens updated
  docs/how-to-apply-ollion-theme.md
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/mixins/scss/_text-tokens.scss
Labels: lgtm, size/L
