Repository ollionorg/flow-core, pull requests merged in 2023-04, with the labels that each got.

#57 FLOW-734 | f-icon-button: hover state bug fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-icon-button/f-icon-button.ts
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#58 ✏️ Updated dependency links + storybook links
  README.md
Labels: lgtm, size/S

#61 ✏️ Updated TS version in readme
  README.md
Labels: lgtm, size/S

#62 FLOW-741 | f-accordion
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-accordion/f-accordion.scss
  packages/flow-core/src/components/f-accordion/f-accordion.test.ts
  packages/flow-core/src/components/f-accordion/f-accordion.ts
  packages/flow-core/src/index.ts
  stories/f-accordion.stories.mdx
  stories/svg/i-faccordion-anatomy.js
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#63 FLOW-749 | f-grid
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-grid/f-grid.scss
  packages/flow-core/src/components/f-grid/f-grid.test.ts
  packages/flow-core/src/components/f-grid/f-grid.ts
  packages/flow-core/src/index.ts
  stories/f-grid.stories.mdx
  stories/svg/i-fgrid-anatomy.js
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#64 FLOW-757 | f-accordion toggle event emission
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-accordion/f-accordion.ts
  stories/f-accordion.stories.mdx
Labels: do-not-merge/contains-merge-commits, lgtm, size/L

#60 FLOW-715 f-carousel
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-accordion/f-accordion.test.ts
  packages/flow-core/src/components/f-carousel-content/f-carousel-content.scss
  packages/flow-core/src/components/f-carousel-content/f-carousel-content.ts
  packages/flow-core/src/components/f-carousel/f-carousel.scss
  packages/flow-core/src/components/f-carousel/f-carousel.test.ts
  packages/flow-core/src/components/f-carousel/f-carousel.ts
  packages/flow-core/src/components/f-carousel/i-fcarousel-example.ts
  packages/flow-core/src/index.ts
  stories/f-carousel.stories.mdx
  stories/svg/i-fcarousel-anatomy.js
  stories/svg/i-fcarousel-example.js
Labels: size/XXL

#66 FLOW-759 | f-div hover bug for child f-div's
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.scss
Labels: do-not-merge/contains-merge-commits, lgtm, size/XL

#65 FLOW-758 Google analytics in storybook
  .storybook/main.js
  .storybook/manager-head.html
  .storybook/manager.js
  package.json
  packages/flow-core/custom-elements.json
  packages/flow-core/src/components/f-carousel/f-carousel.ts
  yarn.lock
Labels: size/XXL
