Repository ollionorg/flow-core, pull requests merged in 2023-09, with the labels that each got.

#133 FLOW-895 | f-counter category addition
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-counter/f-counter.scss
  packages/flow-core/src/components/f-counter/f-counter.test.ts
  packages/flow-core/src/components/f-counter/f-counter.ts
  stories/f-counter.stories.mdx
Labels: do-not-merge/contains-merge-commits, size/XXL, lgtm

#134 FLOW-911 f-input of type number converts zero to blank string
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-input/f-input.ts
  stories/f-input.stories.mdx
Labels: size/XXL

#135 FLOW-912 FLOW-913 clear property fixed in f-date-time-picker and generic types added in flow table
  .husky/pre-commit
  packages/flow-core/CHANGELOG.md
  packages/flow-core/compile.sh
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts
  packages/flow-table/CHANGELOG.md
  packages/flow-table/html.html-data.json
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  stories/f-date-time-picker.stories.mdx
  stories/f-input.stories.mdx
  stories/f-popover.stories.mdx
Labels: size/XXL

#136 FLOW-916 | `f-tag` : counter suraface color visibility fixed.
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-counter/f-counter.scss
Labels: needs-rebase, do-not-merge/contains-merge-commits, size/XXL, lgtm

#138 FLOW-920 | f-select bug fixed for create option
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/render.ts
Labels: size/XXL, lgtm

#139 FLOW-922 | f-file-uplaod Mime Type fix
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-file-upload/f-file-upload.ts
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/utils/index.ts
  packages/flow-core/src/utils/mime-extension-map.ts
Labels: size/XXL, lgtm

#141 FLOW-924 f-select value type fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/render.ts
Labels: size/XXL

#142 FLOW-925 f-search result reactivity issue
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-suggest/f-suggest.ts
Labels: size/XXL, lgtm

#143 FLOW-923 f-select options navigation through arrow keys
  packages/flow-code-editor/custom-elements.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.scss
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/handlers.ts
  packages/flow-core/src/components/f-select/render.ts
  packages/flow-table/custom-elements.json
  stories/f-select.stories.mdx
Labels: size/XXL, lgtm

#144 FLOW-928 | box-shadow for f-popover
  packages/flow-code-editor/custom-elements.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-popover/f-popover.scss
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/mixins/components/f-root/f-root.scss
  packages/flow-table/custom-elements.json
  stories/f-popover.stories.mdx
Labels: size/XXL, lgtm
