Repository ollionorg/flow-core, pull requests merged in 2023-11, with the labels that each got.

#184 FLOW-957 f-table grid template creation bug fixed for vue 3
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table/f-table.ts
Labels: lgtm, size/M

#183 FLOW-947 | f-document-viewer
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-accordion/f-accordion.ts
  packages/flow-core/src/components/f-div/f-div-global.scss
  packages/flow-core/src/components/f-document-viewer/f-document-viewer-global.scss
  packages/flow-core/src/components/f-document-viewer/f-document-viewer.scss
  packages/flow-core/src/components/f-document-viewer/f-document-viewer.test.ts
  packages/flow-core/src/components/f-document-viewer/f-document-viewer.ts
  packages/flow-core/src/components/f-document-viewer/handler.ts
  packages/flow-core/src/components/f-document-viewer/render.ts
  packages/flow-core/src/index.ts
  stories/flow-core/f-document-viewer.mdx
  stories/flow-core/f-document-viewer.stories.ts
  stories/utils/mock-doc-content.ts
Labels: size/XXL, lgtm

#185 FLOW-959 FLOW-960 FLOW-961 state attribute on f-popover and sort event added in f-table-schema
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-popover/f-popover-global.scss
  packages/flow-core/src/components/f-popover/f-popover.test.ts
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/components/f-text/f-text-global.scss
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  stories/flow-core/f-popover.stories.ts
  stories/flow-table/f-table-schema.stories.ts
Labels: lgtm, size/L

#186 FLOW-962 f-popover max-height issue fixed + f-search stories updated
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/components/f-search/f-search.ts
  stories/flow-core/f-search.stories.ts
Labels: size/L

#192 issue-189 f-table-schema: no-data slot added to customise message
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.test.ts
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  stories/flow-table/f-table-schema.stories.ts
Labels: lgtm, size/M

#193 FLOW-964 f-date-picker blur event issue fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts
  stories/flow-form-builder/f-formbuilder-field.ts
Labels: lgtm, size/S

#194 FLOW-964-2 FLOW-964 date parsing error mesasge logic updated
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts
Labels: lgtm, size/M

#191 FLOW-963 | Ollion Themes addition through Figma API's
  .storybook/storybook.css
  packages/flow-core/CHANGELOG.md
  packages/flow-core/figma/sync-colors.js
  packages/flow-core/package.json
  packages/flow-core/src/components/f-text/_f-text-variables-dynamic.scss
  packages/flow-core/src/components/f-text/_f-text-variables.scss
  packages/flow-core/src/components/f-text/f-text-global.scss
  packages/flow-core/src/components/f-text/f-text.scss
  packages/flow-core/src/mixins/components/f-root/f-root-global.scss
  packages/flow-core/src/mixins/scss/_color-tokens.scss
  packages/flow-core/src/mixins/scss/_text-tokens.scss
  pnpm-lock.yaml
Labels: size/XXL, lgtm

#197 FLOW-966 | Text Tokens font-weight bug, requires updation from figma
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-text/_f-text-variables-dynamic.scss
  packages/flow-core/src/mixins/scss/_text-tokens.scss
Labels: lgtm, size/M

#196 FLOW-965 f-input-light element created to fix 1Password autofill issue
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div-global.scss
  packages/flow-core/src/components/f-form-field/f-form-field.ts
  packages/flow-core/src/components/f-input/f-input-base.ts
  packages/flow-core/src/components/f-input/f-input-global.scss
  packages/flow-core/src/components/f-input/f-input-light-global.scss
  packages/flow-core/src/components/f-input/f-input-light.ts
  packages/flow-core/src/components/f-input/f-input.scss
  packages/flow-core/src/components/f-input/f-input.ts
  packages/flow-core/src/index.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/index.ts
  packages/flow-form-builder/src/modules/validation/validator.ts
  stories/flow-core/f-input.mdx
  stories/flow-core/f-input.stories.ts
  stories/flow-form-builder/login-form.stories.ts
Labels: size/XXL, lgtm

#201 FLOW-967 chevron reference added in f-trow
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-trow/f-trow.ts
Labels: lgtm, size/S

#200 FLOW-956 all packages upgraded to lit v3
  package.json
  packages/flow-code-editor/CHANGELOG.md
  packages/flow-code-editor/package.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-lineage/CHANGELOG.md
  packages/flow-lineage/package.json
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-md-editor/package.json
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  pnpm-lock.yaml
  stories/flow-form-builder/login-form.stories.ts
Labels: lgtm, size/L

#202 FLOW-968 `align` property introduced on `f-tcell`.
  packages/flow-core/README.md
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-table-schema/f-table-schema.ts
  packages/flow-table/src/components/f-table/f-table-global.scss
  packages/flow-table/src/components/f-tcell/f-tcell.scss
  packages/flow-table/src/components/f-tcell/f-tcell.ts
  stories/flow-table/f-tcell.stories.ts
  stories/utils/mock-users-data.ts
Labels: lgtm, size/L
