Repository ollionorg/flow-core, pull requests merged in 2023-10, with the labels that each got.

#145 FLOW-930 value property issue in f-select
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-table/custom-elements.json
Labels: size/XXL, lgtm

#146 FLOW-930 `f-select` incrorrect vue2 types generation fixed.
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-table/custom-elements.json
Labels: size/XXL

#148 FLOW-932 display tooltip on f-tag when it has an ellipsis
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-tag/f-tag.ts
Labels: size/XXL

#150 Create lint.yml
  .github/workflows/lint.yml
Labels: size/M

#151 FLOW-940 slack notification meta data updated
  .github/workflows/release.yml
  packages/custom-elements-manifest-to-types/CHANGELOG.md
  packages/custom-elements-manifest-to-types/package.json
  packages/flow-code-editor/CHANGELOG.md
  packages/flow-code-editor/package.json
  packages/flow-core-config/CHANGELOG.md
  packages/flow-core-config/package.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-lineage/CHANGELOG.md
  packages/flow-lineage/package.json
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-md-editor/package.json
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
Labels: lgtm, size/M

#152 fix Fix storybook build by removing sideEffects
  .github/workflows/release.yml
  .storybook/main.ts
  README.md
  package.json
  packages/flow-code-editor/CHANGELOG.md
  packages/flow-code-editor/README.md
  packages/flow-code-editor/package.json
  packages/flow-core-config/CHANGELOG.md
  packages/flow-core-config/package.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/README.md
  packages/flow-core/package.json
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/README.md
  packages/flow-form-builder/package.json
  packages/flow-lineage/CHANGELOG.md
  packages/flow-lineage/README.md
  packages/flow-lineage/package.json
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-md-editor/README.md
  packages/flow-md-editor/package.json
  packages/flow-table/CHANGELOG.md
  packages/flow-table/README.md
  packages/flow-table/package.json
  stories/flow-form-builder/about.mdx
  stories/flow-lineage/introduction/about.mdx
Labels: lgtm, size/L

#153 fix Fix paths to git repo and add documentation
  packages/custom-elements-manifest-to-types/package.json
  packages/flow-code-editor/package.json
  packages/flow-core-config/package.json
  packages/flow-core/package.json
  packages/flow-form-builder/README.md
  packages/flow-form-builder/package.json
  packages/flow-lineage/CHANGELOG.md
  packages/flow-lineage/KNOWN_SOLUTIONS.md
  packages/flow-lineage/README.md
  packages/flow-lineage/package.json
  packages/flow-log/package.json
  packages/flow-md-editor/package.json
  packages/flow-table/package.json
  stories/flow-form-builder/about.mdx
Labels: lgtm, size/M

#155 eslint Add TS generation on post install to avoid state where types a…
  .husky/post-checkout
  .husky/post-merge
  package.json
  pnpm-lock.yaml
Labels: lgtm, size/M

#154 FLOW-939 | f-pictogram adding category prop
  packages/flow-code-editor/CHANGELOG.md
  packages/flow-core-config/CHANGELOG.md
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-pictogram/f-pictogram.scss
  packages/flow-core/src/components/f-pictogram/f-pictogram.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-lineage/CHANGELOG.md
  packages/flow-log/CHANGELOG.md
  packages/flow-md-editor/CHANGELOG.md
  packages/flow-table/CHANGELOG.md
  stories/flow-core/f-pictogram.mdx
  stories/flow-core/f-pictogram.stories.ts
Labels: lgtm, size/L

#162 FLOW-945 v1.8.0 and v1.8.1 commits merged.
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/components/f-form-array/f-form-array.ts
  packages/flow-form-builder/src/modules/validation/validator.ts
  packages/flow-form-builder/src/types.ts
  stories/flow-form-builder/dynamic-validation-message.stories.ts
  stories/flow-form-builder/f-formbuilder-field.ts
Labels: lgtm, size/L, do-not-merge/invalid-pr-title

#164 Issue-157 | FLOW-946 | Disabling option in actions FTcellActions array in every row of f-table-schema
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-tcell/f-tcell.ts
Labels: lgtm, size/S, do-not-merge/invalid-pr-title

#165 issue-156 f-tag width inheritance fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-tag/f-tag-global.scss
  packages/flow-core/src/components/f-tag/f-tag.scss
  stories/flow-core/f-tag.stories.js
Labels: bug, do-not-merge/contains-merge-commits, lgtm, size/S, do-not-merge/invalid-pr-title

#158 feat(ui): FLOW-941 | f-breadcrumbs variant prop introduced
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.scss
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.test.ts
  packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.ts
  stories/flow-core/f-breadcrumb.mdx
  stories/flow-core/f-breadcrumb.stories.ts
Labels: enhancement, lgtm, size/L, do-not-merge/invalid-pr-title

#159 fix: FLOW-944 z-index issue with target , overlay and popover
  packages/flow-code-editor/package.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-popover/f-popover-global.scss
  packages/flow-core/src/components/f-popover/f-popover.scss
  packages/flow-core/src/components/f-popover/f-popover.test.ts
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-form-builder/package.json
  packages/flow-lineage/package.json
  packages/flow-log/package.json
  packages/flow-md-editor/package.json
  packages/flow-table/package.json
  stories/flow-core/f-popover.mdx
  stories/flow-core/f-popover.stories.ts
  stories/tsconfig.json
Labels: bug, lgtm, size/L, do-not-merge/invalid-pr-title

#171 FLOW-948 | f-pictogram auto-bg bug
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-pictogram/f-pictogram.ts
Labels: lgtm, size/M

#172 issue-170 tooltip type updated to accept as object
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/mixins/components/f-root/f-root.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/modules/validation/default-validation-messages/index.ts
  packages/flow-form-builder/src/types.ts
  stories/flow-core/f-tooltip.stories.ts
  stories/flow-form-builder/f-formbuilder-field.ts
Labels: lgtm, size/L

#173 Issue-170 : Duplicate type import fixed
  packages/custom-elements-manifest-to-types/CHANGELOG.md
  packages/custom-elements-manifest-to-types/index.ts
  packages/custom-elements-manifest-to-types/package.json
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
Labels: do-not-merge/contains-merge-commits, lgtm, size/M

#176 FLOW-949 | f-accordion: width out of the bounds wrt parent div in a specific case
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div-global.scss
Labels: lgtm, size/S

#177 issue-175 popover overlay-click event fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-input/f-input.ts
  packages/flow-core/src/components/f-popover/f-popover.ts
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-suggest/f-suggest.ts
Labels: lgtm, size/M

#179 issue-178 f-date-time-picker clear icon behaviour fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.test.ts
  packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts
  packages/flow-core/src/components/f-input/f-input.ts
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/components/f-form-builder/f-form-builder.ts
Labels: lgtm, size/M

#181 issue-180 f-tooltip closable attribute not working fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/mixins/components/f-root/f-root.ts
Labels: lgtm, size/S
