Repository ollionorg/flow-core, pull requests merged in 2023-05, with the labels that each got.

#71 FLOW-770 | Bug Fixes for f-switch and f-accordion
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-accordion/f-accordion.ts
  packages/flow-core/src/components/f-switch/f-switch.scss
  packages/flow-core/src/components/f-switch/f-switch.ts
  stories/f-switch.stories.mdx
Labels: do-not-merge/contains-merge-commits, lgtm, size/XL

#75 FLOW-777 f-select blur event is cutomized to emit only when dropdown closes
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-checkbox/f-checkbox.ts
  packages/flow-core/src/components/f-radio/f-radio.ts
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/handlers.ts
  packages/flow-core/src/components/f-select/render.ts
  stories/f-select.stories.mdx
Labels: size/XL

#77 FLOW-783 | f-select create new option | some bug fixes
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-div/f-div.ts
  packages/flow-core/src/components/f-icon/f-icon.scss
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/render.ts
  packages/flow-core/src/components/f-tag/f-tag.ts
  stories/f-div.stories.mdx
Labels: size/XXL, lgtm

#78 FLOW-784 : f-input | bug-fix - prefix, suffix attribute name
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/html.html-data.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-input/f-input.ts
  packages/flow-core/src/components/f-suggest/f-suggest.ts
Labels: size/XXL, lgtm

#79 FLOW-785 `f-select` : `add-option` event emission logic fixed.
  packages/flow-core/CHANGELOG.md
  packages/flow-core/custom-elements.json
  packages/flow-core/package.json
  packages/flow-core/src/components/f-select/f-select.ts
  packages/flow-core/src/components/f-select/render.ts
Labels: size/XXL
