Repository ollionorg/flow-core, pull requests merged in 2024-03, with the labels that each got.

#245 Externalize lodash-es to reduce bundle size
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/vite.config.ts
Labels: lgtm, size/XS

#247 FDS-654 showWhen not working for 'layout: "label-left" ' fields
  packages/flow-form-builder/CHANGELOG.md
  packages/flow-form-builder/package.json
  packages/flow-form-builder/src/components/f-form-array/f-form-array.ts
  packages/flow-form-builder/src/components/f-form-builder/f-form-builder.ts
  packages/flow-form-builder/src/components/f-form-builder/fields/text.ts
  packages/flow-form-builder/src/components/f-form-object/f-form-object-global.scss
  packages/flow-form-builder/src/components/f-form-object/f-form-object.ts
  packages/flow-form-builder/src/modules/helpers.ts
  stories/flow-form-builder/show-when-with-layout.stories.ts
Labels: lgtm, size/L

#250 FDS-656 tokens updated
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/mixins/scss/_color-tokens.scss
Labels: lgtm, size/L

#252 FDS-657 f-checkbox line-height fixed
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-checkbox/f-checkbox.scss
  packages/flow-table/CHANGELOG.md
  packages/flow-table/package.json
  packages/flow-table/src/components/f-tcell/f-tcell.scss
Labels: lgtm, size/S

#253 FLOW-1477 scroll to keyword in f-log
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-search/f-search.ts
  packages/flow-core/src/components/f-suggest/f-suggest.ts
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log.ts
  stories/flow-core/f-search.stories.ts
  stories/flow-log/logs/logs.js
Labels: size/M

#255 FDS-657 f-log scroll to searchkeyword fixed
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log.ts
Labels: size/S

#257 FDS-657 f-log Not clearing highlight of last search
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log-search-and-filters.ts
  packages/flow-log/src/components/f-log/f-log.ts
Labels: size/S

#259 FDS-660 f-log improvements
  .storybook/preview.ts
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-button/f-button-global.scss
  packages/flow-core/src/components/f-icon-button/f-icon-button-global.scss
  packages/flow-core/src/components/f-tab/f-tab-global.scss
  packages/flow-core/src/components/f-tab/f-tab.ts
  packages/flow-core/src/mixins/scss/_color-tokens.scss
  packages/flow-core/src/mixins/scss/_text-tokens.scss
  packages/flow-log/CHANGELOG.md
  packages/flow-log/package.json
  packages/flow-log/src/components/f-log/f-log-search-and-filters.ts
  packages/flow-log/src/components/f-log/f-log-utils.ts
  packages/flow-log/src/components/f-log/f-log.scss
  packages/flow-log/src/components/f-log/f-log.ts
  stories/flow-core/f-tab.stories.js
  stories/flow-log/f-log.stories.ts
Labels: size/XL

#260 FDS-661 category propetry added to f-tag
  packages/flow-core/CHANGELOG.md
  packages/flow-core/package.json
  packages/flow-core/src/components/f-counter/f-counter.ts
  packages/flow-core/src/components/f-tag/f-tag.scss
  packages/flow-core/src/components/f-tag/f-tag.ts
  stories/flow-core/f-tag.stories.ts
Labels: size/L
